apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: json-api-caller
  title: JSON API Caller Template
  description: Generates JSON from user inputs and makes a POST request
spec:
  owner: user-team
  type: service

  parameters:
    - title: API Request Details
      required:
        - apiUrl
        - envSize
        - environmentName
        - costCenter
        - createdBy
        - adminEmail
        - location
        - subscription
      properties:
        apiUrl:
          title: API URL
          type: string
          description: The API endpoint to send the request to
        envSize:
          title: Environment Size
          type: string
          description: The size of the environment
        environmentName:
          title: Environment Name
          type: string
          description: The name of the environment
        costCenter:
          title: Cost Center
          type: string
          description: The cost center tag
        createdBy:
          title: Created By
          type: string
          description: The creator tag
        adminEmail:
          title: Admin Email
          type: string
          description: Email of the admin user
        location:
          title: Location
          type: string
          description: Cloud provider location
        subscription:
          title: Subscription
          type: string
          description: Subscription owner email

  steps:
    - id: generate-json
      name: Generate JSON
      action: roadiehq:utils:fs:write
      input:
        path: ./generated-payload.json
        content: |
          {
            "EnvSize": "${{ parameters.envSize }}",
            "environmentName": "${{ parameters.environmentName }}",
            "tags": [
              { "costCenter": "${{ parameters.costCenter }}" },
              { "createdBy": "${{ parameters.createdBy }}" }
            ],
            "access": {
              "roles": {
                "admin": "${{ parameters.adminEmail }}"
              }
            },
            "provider": {
              "location": "${{ parameters.location }}",
              "subscription": "${{ parameters.subscription }}",
              "type": "azure"
            }
          }

    - id: call-api
      name: Call API
      action: http:backstage:request
      input:
        method: POST
        url: "${{ parameters.apiUrl }}"
        headers:
          Content-Type: application/json
        bodyFromFile: ./generated-payload.json

  output:
    links:
      - title: API Response
        url: "${{ parameters.apiUrl }}"
