apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: json-api-caller
  title: JSON API Caller Template
  description: Generates JSON from user inputs and makes a POST request
spec:
  owner: user-team
  type: service

  parameters:
    - title: API Request Details
      required:
        - apiUrl
      properties:
        apiUrl:
          title: API URL
          type: string
          description: The API endpoint to send the request to
        envSize:
          title: Environment Size
          type: string
          description: The size of the environment
          default: java-small-env
        environmentName:
          title: Environment Name
          type: string
          description: The name of the environment
          default: aks-test
        costCenter:
          title: Cost Center
          type: string
          description: The cost center tag
          default: Delivery
        createdBy:
          title: Created By
          type: string
          description: The creator tag
          default: Delivery
        adminEmail:
          title: Admin Email
          type: string
          description: Email of the admin user
          default: testuser1@test.com
        location:
          title: Location
          type: string
          description: Cloud provider location
          default: us-east-1
        subscription:
          title: Subscription
          type: string
          description: Subscription owner email
          default: testuser2@test.com

  steps:
    - id: generate-json
      name: Generate JSON
      action: fetch:template
      input:
        url: ./content/api-payload.json  # ✅ Read JSON from a file
        values:
          EnvSize: ${{ parameters.envSize }}
          environmentName: ${{ parameters.environmentName }}
          costCenter: ${{ parameters.costCenter }}
          createdBy: ${{ parameters.createdBy }}
          adminEmail: ${{ parameters.adminEmail }}
          location: ${{ parameters.location }}
          subscription: ${{ parameters.subscription }}

    - id: call-api
      name: Call External API
      action: http:backstage:request
      input:
        method: POST
        path: "/proxy/environment"
        headers:
          Content-Type: application/json
        body: ${{ steps.generate-json.output }}  # ✅ Now it's a valid object

  output:
    links:
      - title: API Response
        url: ${{ parameters.apiUrl }}
