name: Print JSON Input from Third-Party App

on:
  workflow_dispatch:
    inputs:
      json_input:
        description: 'JSON input from third-party app'
        required: true
        default: '{}'

jobs:
  print-json-input:
    runs-on: ubuntu-latest

    steps:
    - name: Print the JSON input passed from third-party app
      run: |
        # Capture the JSON input
        echo "Received JSON input:"
        echo "${{ github.event.inputs.json_input }}"

        # Optionally, parse it (debugging)
        echo "Formatted JSON input:"
        echo "${{ github.event.inputs.json_input }}" | jq . || echo "Invalid JSON input"
